"""empty message

Revision ID: a0fc903b55d0
Revises: 3ff300857ee3
Create Date: 2016-10-23 16:09:32.097063

"""

# revision identifiers, used by Alembic.
revision = 'a0fc903b55d0'
down_revision = '3ff300857ee3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_at')
    ### end Alembic commands ###
