"""empty message

Revision ID: d3af8f1f93d5
Revises: e91416f1802f
Create Date: 2016-10-22 22:50:30.787107

"""

# revision identifiers, used by Alembic.
revision = 'd3af8f1f93d5'
down_revision = 'e91416f1802f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'current_login_ip')
    ### end Alembic commands ###
